=== signal32/blog-next/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "ExternalRequirement": {
            "properties": {
                "href": {
                    "items": [
                        {
                            "type": "string"
                        }
                    ],
                    "maxItems": 1,
                    "minItems": 1,
                    "type": "array"
                },
                "id": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "external"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "InternalRequirement": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "internal"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ProductMedia": {
            "properties": {
                "banner": {
                    "type": "string"
                },
                "gallery": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "videos": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "baseUrl": {
            "type": "string"
        },
        "children": {
            "items": [
                {
                    "type": "string"
                }
            ],
            "maxItems": 1,
            "minItems": 1,
            "type": "array"
        },
        "coverImage": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "excerpt": {
            "type": "string"
        },
        "fileName": {
            "type": "string"
        },
        "files": {
            "properties": {
                "other": {
                    "description": "Miscellaneous files belonging to the product",
                    "items": {
                        "properties": {
                            "slug": {
                                "type": "string"
                            },
                            "tag": {
                                "enum": [
                                    "manual",
                                    "misc"
                                ],
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "type": "array"
                },
                "primary": {
                    "description": "Primary file ID",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "id": {
            "type": "string"
        },
        "media": {
            "$ref": "#/definitions/ProductMedia"
        },
        "modified": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "parent": {
            "type": "string"
        },
        "public": {
            "type": "boolean"
        },
        "published": {
            "format": "date-time",
            "type": "string"
        },
        "requirements": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/ExternalRequirement"
                    },
                    {
                        "$ref": "#/definitions/InternalRequirement"
                    }
                ]
            },
            "type": "array"
        },
        "similar": {
            "items": [
                {
                    "type": "string"
                }
            ],
            "maxItems": 1,
            "minItems": 1,
            "type": "array"
        },
        "slug": {
            "type": "string"
        },
        "thumbnail": {
            "type": "string"
        }
    },
    "type": "object"
}

=== signal32/blog-next/content/products/1--speyside_line/metadata.json
{
    "$schema": "../../../schema.json",
    "id": "speyside_line",
    "name": "The Speyside Line",
    "requirements": [
        {"id": "UKTS Clutter", "site": "UkTrainSim", "href": ["http://uktrainsim.com/"], "type": "external"},
        {"type": "external", "id": "London to Brighton", "site": "Steam", "href": ["http://uktrainsim.com/"]},
        {"type": "internal", "id": "test_product"}
    ],
    "media": {
        "banner": "http://rails.hamishweir.uk/wp-content/uploads/2020/06/ProductBanner_SpeysideLine.jpg",
        "gallery": [
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.43277-3.36209_14-00-35-1920x1080-1.jpg",
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.41212-3.39198_14-01-07-1920x1080-1.jpg",
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.32491-3.53364_18-02-20-1920x1080-1.jpg",
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.24829-3.75247_14-01-56-1920x1080-1.jpg",
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.45819-3.35020_12-00-36-1920x1080-1.jpg",
            "http://rails.hamishweir.uk/wp-content/uploads/2020/07/Screenshot_SB-The-Speyside-Line_57.45140-3.27367_14-09-58-1920x1080-1.jpg"    
        ]
    },
    "files": {
        "primary": "test_file.json",
        "other": [
            {"name": "Test Product Manual", "file": "test_product", "tag": "manual"}
        ]
    }
}
